#alle librarys die gebruikt worden in dit project
library(mongolite)
library(randomcoloR)
library(ggplot2)
library(plotly)
library(dplyr)
library(lubridate)
library(readxl)
library(leaflet)
library(lubridate)
library(randomForest)
library(randomForestExplainer)
library(mgcv)